// Primary webpage accent color
const GLOBAL_ACCENT = 158

const SEMANTIC_COLORS = {
    BACKGROUND_BLACK_BEHIND_MODAL:  'hsla(0, 0%, 0%, 0.75)',
    PAGE_HEADER_GREEN:              `hsl(${GLOBAL_ACCENT}, 50%, 48%)`,

    SIDEBAR_BLACK:                  'hsl(214, 20%, 8%)',
    SIDEBAR_BORDER_BLACK:           'hsl(214, 20%, 21%)',
    SIDEBAR_INACTIVE_TAB_LIGHT:     'hsl(214, 20%, 17%)',
    SIDEBAR_ACTIVE_TAB_GREEN:       `hsl(${GLOBAL_ACCENT}, 70%, 28%)`,
    SIDEBAR_TEXT_ACTIVE_WHITE:      'hsl(0, 0%, 100%)',
    SIDEBAR_TEXT_INACTIVE_WHITE:    'hsl(216, 12%, 84%)',
    SIDEBAR_INACTIVE_TAB_BLANK:     'transparent',
    SIDEBAR_CLOSE_GRAY:             'hsl(218, 11%, 65%)',
    SIDEBAR_CLOSE_GRAY_LIGHT:       'hsl(218, 11%, 80%)',

    ADDITEM_GREEN:          `hsl(${GLOBAL_ACCENT}, 70%, 28%)`,
    ADDITEM_GREEN_DARK:     `hsl(${GLOBAL_ACCENT}, 70%, 20%)`,
    ADDITEM_TEXT_GREEN:     `hsl(${GLOBAL_ACCENT}, 40%, 42%)`,

    ASSIGNMENT_ORANGE:      'hsl(30, 38%, 47%)',
    ASSIGNMENT_ORANGE_DARK: 'hsl(30, 38%, 39%)',
    ASSIGNMENT_TEXT_ORANGE: 'hsl(30, 38%, 47%)',

    EVENT_GREEN:        'hsl(119, 20%, 42%)',
    EVENT_GREEN_DARK:   'hsl(119, 20%, 34%)',
    EVENT_TEXT_GREEN:   'hsl(119, 20%, 42%)',

    NOSCHOOL_BLUE:      'hsl(203, 40%, 44%)',
    NOSCHOOL_BLUE_DARK: 'hsl(203, 40%, 36%)',
    NOSCHOOL_TEXT_BLUE: 'hsl(203, 40%, 44%)',

    CLASS_BLUE:         'hsl(235, 50%, 54%)',
    CLASS_BLUE_DARK:    'hsl(235, 50%, 46%)',
    CLASS_TEXT_BLUE:    'hsl(235, 50%, 54%)',

    CANCEL_GRAY:        'hsl(217, 20%, 27%)',
    CANCEL_GRAY_DARK:   'hsl(217, 20%, 19%)',
    CANCEL_TEXT_GRAY:   'hsl(217, 20%, 60%)',

    DELETE_RED:         'hsl(0, 72%, 51%)',
    DELETE_RED_DARK:    'hsl(0, 72%, 43%)',
    DELETE_TEXT_WHITE:  'hsl(0, 0%, 100%)',
}

// Global Colors
export const GLOBAL = {
    // General
    MODAL_BACKDROP: SEMANTIC_COLORS.BACKGROUND_BLACK_BEHIND_MODAL,
    PAGE_HEADER_TEXT: SEMANTIC_COLORS.PAGE_HEADER_GREEN,
    ADDITEM_HEADER_TEXT: SEMANTIC_COLORS.ADDITEM_TEXT_GREEN,
    MODAL_BG: 'hsl(215, 21%, 10.5%)',
    MODULE_BG: 'hsl(215, 21%, 10.5%)',

    // Sidebar
    SIDEBAR_BG: SEMANTIC_COLORS.SIDEBAR_BLACK,
    SIDEBAR_BORDER: SEMANTIC_COLORS.SIDEBAR_BORDER_BLACK,
    SIDEBAR_TEXT_INACTIVE: SEMANTIC_COLORS.SIDEBAR_TEXT_INACTIVE_WHITE,
    SIDEBAR_TEXT_ACTIVE: SEMANTIC_COLORS.SIDEBAR_TEXT_ACTIVE_WHITE,
    SIDEBAR_ACTIVE_TAB_GREEN_BG: SEMANTIC_COLORS.SIDEBAR_ACTIVE_TAB_GREEN,
    SIDEBAR_INACTIVE_TAB_BLANK_BG: SEMANTIC_COLORS.SIDEBAR_INACTIVE_TAB_BLANK,
    SIDEBAR_INACTIVE_TAB_BLANK_BG_HOVER: SEMANTIC_COLORS.SIDEBAR_INACTIVE_TAB_LIGHT,
    SIDEBAR_CLOSE_ICON: SEMANTIC_COLORS.SIDEBAR_CLOSE_GRAY,
    SIDEBAR_CLOSE_ICON_HOVER: SEMANTIC_COLORS.SIDEBAR_CLOSE_GRAY_LIGHT,

    // Add Item button colors
    ADDITEM_BUTTON_BG: SEMANTIC_COLORS.ADDITEM_GREEN,
    ADDITEM_BUTTON_BG_HOVER: SEMANTIC_COLORS.ADDITEM_GREEN_DARK,
    
    // Text colors
    ASSIGNMENT_HEADING_TEXT: SEMANTIC_COLORS.ASSIGNMENT_TEXT_ORANGE,
    EVENT_HEADING_TEXT: SEMANTIC_COLORS.EVENT_TEXT_GREEN,
    NOSCHOOL_HEADING_TEXT: SEMANTIC_COLORS.NOSCHOOL_TEXT_BLUE,
    CLASS_HEADING_TEXT: SEMANTIC_COLORS.CLASS_TEXT_BLUE,

    // Assignment-related colors
    ASSIGNMENT_BUTTON_BG: SEMANTIC_COLORS.ASSIGNMENT_ORANGE,
    ASSIGNMENT_BUTTON_BG_HOVER: SEMANTIC_COLORS.ASSIGNMENT_ORANGE_DARK,
    // Event-related colors
    EVENT_BUTTON_BG: SEMANTIC_COLORS.EVENT_GREEN,
    EVENT_BUTTON_BG_HOVER: SEMANTIC_COLORS.EVENT_GREEN_DARK,
    // No School-related colors
    NOSCHOOL_BUTTON_BG: SEMANTIC_COLORS.NOSCHOOL_BLUE,
    NOSCHOOL_BUTTON_BG_HOVER: SEMANTIC_COLORS.NOSCHOOL_BLUE_DARK,
    // Class-related colors
    CLASS_BUTTON_BG: SEMANTIC_COLORS.CLASS_BLUE,
    CLASS_BUTTON_BG_HOVER: SEMANTIC_COLORS.CLASS_BLUE_DARK,
    // Cancel button colors
    CANCEL_BUTTON_BG: SEMANTIC_COLORS.CANCEL_GRAY,
    CANCEL_BUTTON_BG_HOVER: SEMANTIC_COLORS.CANCEL_GRAY_DARK,
    CANCEL_BUTTON_TEXT: SEMANTIC_COLORS.CANCEL_TEXT_GRAY,
    // Delete button colors
    DELETE_BUTTON_BG: SEMANTIC_COLORS.DELETE_RED,
    DELETE_BUTTON_BG_HOVER: SEMANTIC_COLORS.DELETE_RED_DARK,
    DELETE_BUTTON_TEXT: SEMANTIC_COLORS.DELETE_TEXT_WHITE,
}

// Dashboard page
export const DASHBOARD = {
    // General
    MODULE_BG: 'hsl(215, 21%, 9.5%)',

    // General Text Colors
    TEXT_GRAY_400: '#9ca3af',
    TEXT_GRAY_500: '#6b7280',
    TEXT_WHITE: '#ffffff',
    NO_SCHOOL_TEXT: '#f87171',
    // Priority Colors
    PRIORITY_HIGH: '#f87171',
    PRIORITY_MEDIUM: '#facc15',
    PRIORITY_LOW: '#60a5fa',
    // Icon Colors
    ICON_PLAY_DEFAULT: '#6b7280',
    ICON_PLAY_HOVER: '#a78bfa',
    ICON_IN_PROGRESS: '#fb923c',
    ICON_IN_PROGRESS_HOVER: '#22c55e',
    ICON_COMPLETE: '#22c55e',
    ICON_COMPLETE_HOVER: '#6b7280',

    // Today's Assignments Box
    CLASS_ITEM_BG: '#161b22',
    CLASS_ITEM_HOVER_BG: '#1c2128',
    // Today's Events Box
    EVENT_ITEM_BG: '#161b22',
    EVENT_ITEM_HOVER_BG: '#1c2128'
}

// Calendar page
export const CALENDAR = {
    // General
    BG_COLOR: GLOBAL.MODULE_BG,
    BORDER_COLOR: '#30363d',

    // Header
    HEADER_TEXT: '#ffffff',
    HEADER_ICON: '#a78bfa',
    HEADER_BUTTON_HOVER: '#374151',

    // Headings
    ASSIGNMENT_HEADING: GLOBAL.ASSIGNMENT_HEADING_TEXT,
    EVENT_HEADING: GLOBAL.EVENT_HEADING_TEXT,
    CLASS_HEADING: GLOBAL.CLASS_HEADING_TEXT,
    NO_SCHOOL_HEADING: GLOBAL.NOSCHOOL_HEADING_TEXT,

    // Grid
    GRID_BORDER: '#30363d',
    DAY_HEADER_BG: '#111418',
    DAY_HEADER_TEXT: '#9ca3af',

    // Day Cell
    DAY_BG: 'transparent',
    DAY_BG_HOVER: '#374151',
    DAY_INACTIVE_BG: '#0d1117',
    DAY_INACTIVE_TEXT: '#4b5563',
    DAY_NUMBER_TEXT: '#d1d5db',

    // Today
    TODAY_BG: '#22252a',
    TODAY_BORDER: SEMANTIC_COLORS.SIDEBAR_ACTIVE_TAB_GREEN,

    // No School
    NO_SCHOOL_BG: 'rgba(55, 65, 81, 0.3)',
    NO_SCHOOL_BORDER: 'rgba(75, 85, 99, 0.4)',
    NO_SCHOOL_TEXT: '#9ca3af',

    // Side Panel
    SIDE_PANEL_BG: '#1f2937',
    SIDE_PANEL_BORDER: '#374151',
    SIDE_PANEL_TEXT: '#ffffff',
    SIDE_PANEL_DIM_TEXT: '#9ca3af',
    SIDE_PANEL_CLOSE_ICON: '#9ca3af',
    SIDE_PANEL_CLOSE_ICON_HOVER: '#ffffff',

    // Side Panel - Items
    ITEM_BG: '#374151',
    ITEM_BG_HOVER: '#4b5563',

    // Day Types
    A_DAY_TEXT: '#c4b5fd',
    B_DAY_TEXT: '#93c5fd',

    // Priorities & Status
    PRIORITY_HIGH_BG: '#7f1d1d',
    PRIORITY_HIGH_TEXT: '#fca5a5',
    PRIORITY_MEDIUM_BG: '#7c2d12',
    PRIORITY_MEDIUM_TEXT: '#fdba74',
    PRIORITY_LOW_BG: '#1f2937',
    PRIORITY_LOW_TEXT: '#d1d5db',

    STATUS_DONE_TEXT: '#9ca3af',
    STATUS_DONE_TAG_BG: '#374151',
    STATUS_DONE_TAG_TEXT: 'rgba(34, 197, 94, 0.6)',
    STATUS_DONE_TAG_BORDER: 'rgba(34, 197, 94, 0.6)',

    // Default Class Color
    DEFAULT_CLASS_COLOR: '#8957e5',
}

// My Assignments page
export const MY_ASSIGNMENTS = {
    BOARD_BG: GLOBAL.MODULE_BG
}

// My Classes page
export const MY_CLASSES = {
    CLASS_TEXT_THEME: SEMANTIC_COLORS.CLASS_TEXT_BLUE,
    CLASS_TEXT_THEME_HOVER: SEMANTIC_COLORS.CLASS_BLUE_DARK,
    CLASS_MODAL_BUTTON_BG: SEMANTIC_COLORS.CLASS_BLUE,
    CLASS_MODAL_BUTTON_BG_HOVER: SEMANTIC_COLORS.CLASS_BLUE_DARK,
    CLASS_CARD_BG: GLOBAL.MODULE_BG,
    CLASS_COLORS: [
        'hsl(0, 75%, 57%)', 'hsl(10, 75%, 57%)', 'hsl(25, 75%, 57%)', 'hsl(38, 75%, 57%)',
        'hsl(60, 75%, 57%)', 'hsl(142, 75%, 57%)', 'hsl(173, 75%, 57%)', 'hsl(199, 75%, 57%)',
        'hsl(217, 75%, 57%)', 'hsl(239, 75%, 57%)', 'hsl(258, 75%, 57%)', 'hsl(292, 75%, 57%)',
        'hsl(330, 75%, 57%)',
    ]
}

// My Schedule page
export const MY_SCHEDULE = {
    REMOVE_BUTTON_BG: SEMANTIC_COLORS.DELETE_RED,
    REMOVE_BUTTON_BG_HOVER: SEMANTIC_COLORS.DELETE_RED_DARK,
    REMOVE_BUTTON_TEXT: SEMANTIC_COLORS.DELETE_TEXT_WHITE,
    MODULE_BG: GLOBAL.MODULE_BG
}

// Settings page
export const SETTINGS = {
    SCHEDULE_SETTINGS_HEADER: SEMANTIC_COLORS.CLASS_TEXT_BLUE,
    MODULE_BG: GLOBAL.MODULE_BG
}